{ config, lib, pkgs, ... }:
with lib;
let
  cfg = config.make.host.boot;
in {

  options.make.host.boot.initrd = {
    
  };

  config = {
    boot.initrd = {
      # disabling verbosity removes only the mandatory messages generated by the NixOS
      verbose = false;
      systemd = {
        # enable systemd in initrd (experimental)
        enable = true;
        # strip copied binaries and libraries from inframs
        # saves some nice space
        strip = true;
        # Prefer the system to attempt to continue booting so
        # that we can hopefully still access it remotely.
        emergencyAccess = false;
        suppressedUnits = mkIf config.systemd.enableEmergencyMode [
          "emergency.service"
          "emergency.target"
        ];
      };
      kernelModules = [
        "nvme"
        "xhci_pci"
        "ahci"
        "btrfs"
        "sd_mod"
        "dm_mod"
      ];
      availableKernelModules = [
        "vmd"
        "usbhid"
        "sd_mod"
        "sr_mod"
        "dm_mod"
        "uas"
        "usb_storage"
        "rtsx_usb_sdmmc"
        "rtsx_pci_sdmmc" # Realtek SD card interface (btw i hate realtek)
        "ata_piix"
        "virtio_pci"
        "virtio_scsi"
        "ehci_pci"
      ];
      # NOTE: This includes my authorization keys
      network.ssh.authorizedKeyFiles = with inputs; [ my-keys.outPath ];
    };
  };
}