name: Build WG Registry

on:
  push:
    paths:
      - '**.nix'
      - '.github/workflows/wg-registry.yml'
  workflow_dispatch: {}
  schedule:
    - cron: '19 */6 * * *' # rebuild every 6h
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          
      - name: Install Colmena
        run: nix-env -if https://github.com/zhaofengli/colmena/tarball/main
        
      - name: Evaluate hive -> wg-registry.json
        run: |
          mkdir -p systems
          colmena eval scripts/wg-registry.nix > systems/wg-registry.json
          
      - name: Commit & push registry (if changed)
        run: |
          if git diff --quiet -- systems/wg-registry.json; then
            echo "No changes to registry."
            exit 0
          fi
          git config user.name "wg-registry-bot"
          git config user.email "wg-registry-bot@users.noreply.github.com"
          git add hosts/wg-registry.json
          git commit -m "chore(wg): update peer registry"
          git push
