name: Build WG Registry

on:
  push:
    paths:
      - '**.nix'
      - '.github/workflows/wg-registry.yml'
  workflow_dispatch: {}
  schedule:
    - cron: '19 */6 * * *' # rebuild every 6h
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
          
      - name: Use nix-community Cachix
        uses: cachix/cachix-action@v14
        with:
          name: nix-community
        
      - name: Evaluate hive → wg-registry.json
        run: |
          mkdir -p systems
          nix run nixpkgs#colmena -- eval scripts/wg-registry.nix > systems/wg-registry.json

          
      - name: Commit & push registry (if changed)
        run: |
          if git diff --quiet -- systems/wg-registry.json; then
            echo "No changes to registry."
            exit 0
          fi
          git config user.name "wg-registry-bot"
          git config user.email "wg-registry-bot@users.noreply.github.com"
          git add systems/wg-registry.json
          git commit -m "chore(wg): update peer registry"
          git push
